<?php

namespace Eduardoks98\AdsFacebook\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Str;
use Eduardoks98\Monetization\Services\RewardService;
use Eduardoks98\Monetization\Models\AdImpression;
use Eduardoks98\Monetization\Enums\AdProvider;
use Eduardoks98\Monetization\Enums\RewardType;

/**
 * Controller for client-side reward reporting.
 *
 * Since Facebook Audience Network doesn't have S2S callbacks,
 * this controller provides an endpoint for your mobile app
 * to report completed rewarded ads.
 *
 * IMPORTANT: This should be protected by authentication
 * to prevent abuse.
 */
class FanRewardController extends Controller
{
    public function __construct(
        protected RewardService $rewardService
    ) {}

    /**
     * Handle reward from client.
     *
     * Expected request body:
     * - placement_id: FAN placement ID
     * - transaction_id: Unique transaction ID (generated by app)
     * - reward_item: Reward item name (optional)
     * - reward_amount: Reward amount (optional)
     * - metadata: Additional metadata (optional)
     */
    public function handle(Request $request): JsonResponse
    {
        if (!config('ads-facebook.rewards.enabled', true)) {
            return response()->json(['error' => 'Rewards disabled'], 403);
        }

        // Validate request
        $validated = $request->validate([
            'placement_id' => 'required|string|max:255',
            'transaction_id' => 'required|string|max:255',
            'reward_item' => 'nullable|string|max:100',
            'reward_amount' => 'nullable|integer|min:1|max:10000',
            'metadata' => 'nullable|array',
        ]);

        $user = $request->user();

        if (!$user) {
            if (config('ads-facebook.rewards.require_auth', true)) {
                return response()->json(['error' => 'Authentication required'], 401);
            }

            // Without auth, we can't process rewards
            $this->logCallback('error', 'No authenticated user');
            return response()->json(['error' => 'User not found'], 400);
        }

        $placementId = $validated['placement_id'];
        $transactionId = $validated['transaction_id'];
        $rewardItem = $validated['reward_item'] ?? config('ads-facebook.rewards.default_item', 'coins');
        $rewardAmount = $validated['reward_amount'] ?? config('ads-facebook.rewards.default_amount', 10);
        $metadata = $validated['metadata'] ?? [];

        // Check for duplicate transaction
        $existingReward = $this->rewardService->findByTransaction(AdProvider::FACEBOOK, $transactionId);
        if ($existingReward) {
            $this->logCallback('info', 'Duplicate transaction detected', [
                'transaction_id' => $transactionId,
                'user_id' => $user->id,
            ]);
            return response()->json([
                'success' => false,
                'message' => 'Duplicate transaction',
            ], 200);
        }

        try {
            // Track the impression
            if (config('monetization.impressions.enabled', true)) {
                AdImpression::create([
                    'user_id' => $user->id,
                    'provider' => AdProvider::FACEBOOK,
                    'ad_unit_id' => $placementId,
                    'ad_type' => 'rewarded',
                    'placement' => $placementId,
                    'transaction_id' => $transactionId,
                    'platform' => $this->detectPlatform($request),
                    'ip_address' => config('monetization.impressions.track_ip') ? $request->ip() : null,
                    'user_agent' => config('monetization.impressions.track_user_agent') ? $request->userAgent() : null,
                    'metadata' => $metadata,
                ]);
            }

            // Create and process the reward
            if (config('ads-facebook.rewards.sync_processing', false)) {
                $reward = $this->rewardService->createReward(
                    userId: $user->id,
                    provider: AdProvider::FACEBOOK,
                    transactionId: $transactionId,
                    rewardItem: $rewardItem,
                    rewardAmount: $rewardAmount,
                    adUnitId: $placementId,
                    rewardType: RewardType::CURRENCY,
                    metadata: array_merge($metadata, [
                        'source' => 'client_report',
                    ])
                );
                $this->rewardService->processReward($reward);
            } else {
                $reward = $this->rewardService->createAndDispatch(
                    userId: $user->id,
                    provider: AdProvider::FACEBOOK,
                    transactionId: $transactionId,
                    rewardItem: $rewardItem,
                    rewardAmount: $rewardAmount,
                    adUnitId: $placementId,
                    rewardType: RewardType::CURRENCY,
                    metadata: array_merge($metadata, [
                        'source' => 'client_report',
                    ])
                );
            }

            $this->logCallback('info', 'Reward created successfully', [
                'user_id' => $user->id,
                'transaction_id' => $transactionId,
                'amount' => $rewardAmount,
            ]);

            return response()->json([
                'success' => true,
                'reward_id' => $reward->id,
                'amount' => $rewardAmount,
                'item' => $rewardItem,
            ]);

        } catch (\Exception $e) {
            $this->logCallback('error', 'Failed to process reward', [
                'error' => $e->getMessage(),
                'transaction_id' => $transactionId,
                'user_id' => $user->id,
            ]);

            return response()->json([
                'success' => false,
                'message' => 'Failed to process reward',
            ], 500);
        }
    }

    /**
     * Generate a transaction ID for the client.
     *
     * This endpoint can be called before showing an ad
     * to get a unique transaction ID.
     */
    public function generateTransactionId(Request $request): JsonResponse
    {
        $user = $request->user();

        $transactionId = 'fan_' . ($user?->id ?? 'anon') . '_' . Str::uuid()->toString();

        return response()->json([
            'transaction_id' => $transactionId,
        ]);
    }

    /**
     * Detect platform from user agent.
     */
    protected function detectPlatform(Request $request): ?string
    {
        $userAgent = strtolower($request->userAgent() ?? '');

        if (str_contains($userAgent, 'android')) {
            return 'android';
        }

        if (str_contains($userAgent, 'iphone') || str_contains($userAgent, 'ipad')) {
            return 'ios';
        }

        return null;
    }

    /**
     * Log callback event.
     */
    protected function logCallback(string $level, string $message, array $context = []): void
    {
        if (!config('ads-facebook.logging.enabled', true)) {
            return;
        }

        if ($level === 'info' && !config('ads-facebook.logging.log_success', true)) {
            return;
        }

        $channel = config('ads-facebook.logging.channel');
        $logger = $channel ? Log::channel($channel) : Log::getFacadeRoot();

        $logger->$level("Facebook FAN: {$message}", $context);
    }
}
